const questions = {
	1: {
		qno: 1,
		question: "What is your smoking status?",
		options: ["Ex-smoker(1 year)", "Current smoker", "Non-smoker"],
		nextQnos: [2],
	},
	2: {
		qno: 2,
		question: "Do you have repeated episodes of cough?",
		options: ["Yes", "No"],
		nextQnos: [3, 5],
	},
	3: {
		qno: 3,
		question: "How many times in a year cough-episode occurs?",
		options: ["1", "2", "3", ">3"],
		nextQnos: [4],
	},
	4: {
		qno: 4,
		question: "How long does each episode last?",
		options: ["less that 3 times", "more than 3 times"],
		nextQnos: [5],
	},
	5: {
		qno: 5,
		question: "Have you been diagnosed with Asthma?",
		options: ["Yes", "No"],
		nextQnos: [6, 19],
	},
	6: {
		qno: 6,
		question: "Wheeze and chest tightness present?",
		options: ["Yes", "No"],
		nextQnos: [7, 11],
	},
	7: {
		qno: 7,
		question: "For how long is the wheeze present? (days)",
		options: [],
		nextQnos: [8],
	},
	8: {
		qno: 8,
		question: "Do you experience episodic or continuous wheeze?",
		options: ["Episodic", "Continuous", "Can't say"],
		nextQnos: [9],
	},
	9: {
		qno: 9,
		question: "Does your wheeze vary with seasons?",
		options: ["Yes", "No"],
		nextQnos: [10],
	},
	10: {
		qno: 10,
		question: "Does your wheeze vary across the day?",
		options: ["Yes", "No"],
		nextQnos: [11],
	},
	11: {
		qno: 11,
		question: "Do you have cough?",
		options: ["Yes", "No"],
		nextQnos: [12, 14],
	},
	12: {
		qno: 12,
		question: "Do you have dry or wet cough?",
		options: ["Wet", "Dry"],
		nextQnos: [13, 14],
	},
	13: {
		qno: 13,
		question: "Sputum color",
		options: ["White", "Yellow", "Green"],
		nextQnos: [14],
	},
	14: {
		qno: 14,
		question: "Are you under any medication for asthma?",
		options: ["Yes", "No"],
		nextQnos: [15],
	},
	15: {
		qno: 15,
		question: "Do you use inhalers or nebulizers?",
		options: ["Inhalers", "Nebulizers", "Both", "Don't use anything"],
		nextQnos: [16],
	},
	16: {
		qno: 16,
		question: "Do you have family history of asthma?",
		options: ["Yes", "No"],
		nextQnos: [17],
	},
	17: {
		qno: 17,
		question: "Do you have allergies?",
		options: ["Yes", "No"],
		nextQnos: [18, 19],
	},
	18: {
		qno: 18,
		question: "Triggers for allergies?",
		options: [
			"No Triggers",
			"Pollution",
			"Strong smells",
			"Pollen",
			"Other",
		],
		nextQnos: [19],
	},
	19: {
		qno: 19,
		question: "Have you suffered from lung TB in the past?",
		options: ["Yes", "No"],
		nextQnos: [20],
	},
	20: {
		qno: 20,
		question: "Do you have any other respiratory illness?",
		options: ["Yes", "No"],
		nextQnos: [21, 22],
	},
	21: {
		qno: 21,
		question: "Write in brief About it",
		options: [],
		nextQnos: [22],
	},
	22: {
		qno: 22,
		question: "Are you a known case of high blood pressure?",
		options: ["Yes", "No"],
		nextQnos: [23, 24],
	},
	23: {
		qno: 23,
		question: "Your high blood pressure is",
		options: ["Well controlled", "Nearly controlled"],
		nextQnos: [24],
	},
	24: {
		qno: 24,
		question: "Are you a known case of diabetes?",
		options: ["Yes", "No"],
		nextQnos: [25, 26],
	},
	25: {
		qno: 25,
		question: "Your diabetes is",
		options: ["Well controlled", "Nearly controlled"],
		nextQnos: [26],
	},
	26: {
		qno: 26,
		question: "Are you a known case of heart disease?",
		options: ["Yes", "No"],
		nextQnos: [27],
	},
	27: {
		qno: 27,
		question: "Any other health problems?",
		options: ["Yes", "No"],
		nextQnos: [28, 29],
	},
	28: {
		qno: 28,
		question: "What health problems?",
		options: [],
		nextQnos: [29],
	},
	29: {
		qno: 29,
		question: "Are you currently COVID-19 positive or have common cold?",
		options: ["Yes", "No"],
		nextQnos: [30],
	},
	30: {
		qno: 30,
		question:
			"Have you been COVID-19 positive or had cold in last 15 days?",
		options: ["Yes", "No"],
		nextQnos: [-1],
	},
};

module.exports = { questions };
